### ISSUE TITLE
Commands evaluate with newlines

### ISSUE THREAD

**Issue by violine1101** [mojira/arisa-kt#533]
## The Bug
The command only works if it is the only thing in the comment.

## Example Ticket
https://bugs.mojang.com/browse/MC-197177

## Expected behavior
Evaluate every line in a comment separately?

**Comment by violine1101** [comment]
Might have been fixed by #465, will need to test that

**Comment by SPGoding** [comment]
#465 only improves the error message (see [here](https://bugs.mojang.com/browse/MCTEST-116?focusedCommentId=921807&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-921807)); it still doesn't allow containing things other than command in a comment.
